export const homeItems = [
  { image: '/feature-category/cat-1.png', title: 'Mango Madness', items: 12 },
  { image: '/feature-category/cat-2.png', title: 'Banana Bonanza', items: 5 },
  { image: '/feature-category/cat-3.png', title: 'Orange Zest', items: 17 },
  { image: '/feature-category/cat-11.png', title: 'Blueberry Burst', items: 16 },
  { image: '/feature-category/cat-12.png', title: 'Peach Perfection', items: 11 },
  { image: '/feature-category/cat-14.png', title: 'Plum Pleasure', items: 18 },
  { image: '/feature-category/cat-13.png', title: 'Apricot Aroma', items: 6 },
  { image: '/feature-category/cat-14.png', title: 'Plum Pleasure', items: 18 },
  { image: '/feature-category/cat-9.png', title: 'Cherry Cheer', items: 20 },
  { image: '/feature-category/cat-15.png', title: 'Watermelon Wave', items: 4 },
  { image: '/feature-category/cat-14.png', title: 'Plum Pleasure', items: 18 },
  { image: '/feature-category/cat-4.png', title: 'Pineapple Paradise', items: 8 },
  { image: '/feature-category/cat-5.png', title: 'Grapes Galore', items: 3 },
  { image: '/feature-category/cat-9.png', title: 'Cherry Cheer', items: 20 },
  { image: '/feature-category/cat-11.png', title: 'Blueberry Burst', items: 16 },
  { image: '/feature-category/cat-12.png', title: 'Peach Perfection', items: 11 },
  { image: '/feature-category/cat-14.png', title: 'Plum Pleasure', items: 18 },
  { image: '/feature-category/cat-13.png', title: 'Apricot Aroma', items: 6 },
  { image: '/feature-category/cat-14.png', title: 'Plum Pleasure', items: 18 },
  { image: '/feature-category/cat-9.png', title: 'Cherry Cheer', items: 20 },
  { image: '/feature-category/cat-15.png', title: 'Watermelon Wave', items: 4 },
  { image: '/feature-category/cat-14.png', title: 'Plum Pleasure', items: 18 },
];